var pilgrim = [
  "...Is chicken parmesan vegan?",
  "...Lesbians?",
  "...She has to go. She knows we suck.",
  "[Drummer]",
  "[Has issues]",
  "[He really doesn't.]",
  "[Knows everyone including you]",
  "[Lives here]",
  "[Rating: 7.5/10 Fun fact: He is gay]",
  "[Rating: Awesome]",
  "[Rating: T for Teen]",
  "[The Talent]",
  "[The happiest day of his life]",
  "[Status: Scott is an idiot]",
  "17 years old? Scandal.",
  "A sheep?? Are you serious? Draw me a sheep!",
  "A tiny robot is kicking this guy's ass, if anyone wants to watch. Oh, and then the band's gonna play.",
  "Actually, muchacho, I poured the soy in this cup, but I thought real hard about pouring it in that cup. You know, in my \"mind's eye\" or whatever.",
  "Ah, that sucks, but you know it's probably just because he's better than you.",
  "All of our shows are secret shows.",
  "All right, this next song goes out to the guy who keeps yelling from the balcony. It's called \"We Hate You, Please Die.\"",
  "Amazon.ca, what's the website for that?",
  "Amazon.ca.",
  "And a dorky hat!!",
  "And Kim... I'm sorry about everything. I'm sorry about me.",
  "And the cleaning lady... cleans up... dust. She dusts. And she has weekends off, so... Monday. Right?",
  "And you didn't bang her? Are you gay?",
  "And you're not a fat-ass. She didn't mean that. So, are we all good?",
  "Anyone can be vegan.",
  "Are there... Romans there?",
  "Are you a pirate?",
  "Are you kidding? It's, like, ambrosia.",
  "Are you serious? There are, like, 200 steps, and the rails are garbage.",
  "At 12:27 am, on February 1st, you knowingly ingested gelato.",
  "At least I... Wait... Something... You... insult...",
  "Attack hug!!",
  "Aw, I didn't get his autograph.",
  "Aw, I think this deserves a song. Kimberley!!",
  "Aww... Wait! What? This sucks! You suck!",
  "Awww, I'm always there for my little brother's crappy band's shows, you know that!",
  "Awww, man? That one band with Crash? And those boys? I hate them!",
  "Back off, bitch, it's my birthday.",
  "Back off, has-bian!",
  "Basically, you can't win this fight, so you're gonna have to give up on this girl, 'cause Todd's gonna kill you.",
  "Because bread makes you fat.",
  "Because I'll be pulverizing you sometime over the weekend.",
  "Because I'm in love with her.",
  "Because you'll be dust by Monday.",
  "Because you'll be pulverized in two seconds. And the cleaning lady? She cleans up dust. She dusts.",
  "Because... because you'll be dust on Monday.",
  "Boy, does she know me.",
  "Bread makes you fat.",
  "Bread makes you fat??",
  "But are you a pretty good skater?",
  "But can you do a thingy...on that rail?",
  "But if I sign for it you'll leave.",
  "But there was this girl...",
  "But there's so much food!",
  "But-But this is only my first offense. Don't I get three strikes? I mean...",
  "Can we skip the dream time? Color me not interested.",
  "Canada was never supposed to get this hot, dude.",
  "Chicken isn't vegan?",
  "Chill out. It's like in Trainspotting.",
  "Ciao, Knives.",
  "Cool, I'll make a note of that.",
  "Dear Mr. Pilgrim, it has come to my attention that we will be fighting soon. My name is Matthew Patel, and... Blah, blah, blah, b... Fair warning... Mano y mano... Seven evil... Blah, blah... This is...  This is... This is... This is boring. Dele-ete.",
  "Did you learn that at Vegan Academy?",
  "Did you make some of those up?",
  "Didn't you get my email explaining the situation?",
  "Didn't you know? Todd's vegan.",
  "Do that again, and I will end you!",
  "Do you always refer to him by his full name?",
  "Do you know a girl with hair like this?",
  "Do you know anything about cats?",
  "Do you know anything at all about Rome? You don't, do you?",
  "Does that mean we can make out?",
  "Don't be a bitch, bitch!",
  "DON'T SWEAT IT! ENVY'S ALL LOOKS! SHE'S JUST A PRETTY-BOY!",
  "Don't worry, I know what I'm doing. Stephen, the new line-up rocks. You guys sound way better without me. Young Neil, you have learned well. From this point forward, you will be known as... Neil.",
  "Don't you just wish this moment could last forever?",
  "Don't you talk to me about grammar.",
  "Dude, I can see in your mind's eye, that you put half-and-half into one of those coffees, in an attempt to make me break Vegan-edge. I'll take the one with soy.  Thanks, tool.",
  "Dude, now I'm reading it!",
  "Dude, now I'm totally reading it.",
  "Dude, the computer claims I have mail!",
  "Dude, this thing claims I have mail.",
  "Dude, you could ask.",
  "Evil? You mean, do I have, like, ulterior motives? I'm offended, Kim.",
  "Exes.",
  "Fight your own battles, lazy ass!",
  "For the record, I am so pissed off for you, right now.",
  "Freeze! Vegan Police!",
  "Fun? In Toronto?",
  "Garlic bread is my favourite food. I could honestly eat it for every meal. Or just all the time without even stopping.",
  "Geez, buddy, it's gonna be all right!",
  "Gelato isn't vegan?",
  "Gideon stole the Power of Love! What a dick!",
  "Girl...",
  "Give it a rest, Ramona! This is a League game!",
  "Go ahead and get snippy, baby. If you knew the science, maybe I'd listen to a word you're saying.",
  "Go ahead. I'm too cool for you anyway.",
  "Go to the other end of the book and start at page 1.",
  "Good evening. I am Crash, and these are the boys.",
  "Good evening. My name is Crash, and these are the Boys.",
  "Guess who's drunk!",
  "Hate you. Even I would think twice about dating a 17-year-old.",
  "Have you dumped everyone you've ever been with? You've never been the dumpee?",
  "Have you seen the grease oozing from that vent outside?",
  "He and me.",
  "He had snot in his nose? But he's famous.",
  "He really doesn't know!",
  "He was a snot-nosed little brat. He just followed me around.",
  "He works in a restaurant, Scott, but nice try.",
  "Heat wave? Oh yeah... I guess I'm drenched in sweat...",
  "Heh. I'm sorry, but that's pathetic.",
  "Hell, yes, we are. And it's HILARIOUS!",
  "Her weak point is the back of her knees.",
  "He's going for the air juggle!",
  "He's not even conscious!",
  "Hey so, can this not be a one-night stand? For one thing I didn't even get any. That was a joke.",
  "Hey! Attack hug. That's so cute. So cute.",
  "Hey! Hey. Mind if I tag along?",
  "Hey, Amazon.ca, that's the online bookstore or whatever, right?",
  "Hey, don't worry. I don't even know what I'm like anymore.",
  "Hey, Jimmy. Do they rock or suck?",
  "Hey, Knives. This is my cool, gay roommate, Wallace Wells. He's gay.",
  "Hey, lovebirds. We have unfinished business, I and he.",
  "Hey, man, question. I always wondered, how does not eating dairy products give you psychic powers?",
  "Hey, pal! I just wanna say I feel terrible about earlier. I don't want any hard feelings, so I figured, why not be the bigger man, and just give you a call.",
  "Hey, you know Pac-man?",
  "Hey, you totally came!",
  "Hey... me neither.",
  "Hi. Big fan.",
  "Hi. I was thinking about asking you out, but then I realized how stupid that would be. So do you want to go out sometime?",
  "How am I suppose to know, It's unknown!! Your Age is Unknown!!",
  "How are we supposed to follow this? We're not going to win. We're not going to sign with G-Man. We'll never play opening night at the Chaos Theatre. GODDAMN IT, SCOTT! WILL YOU PLEASE STOP JUST STANDING THERE?! YOU'RE FREAKING ME OUT!",
  "How are you doing that with your mouth?",
  "How's it going back there?",
  "Hurt, Kim.",
  "I believe I broke up with her.",
  "I can not... have... tea.",
  "I can't believe you're drinking beer! Is this the transformative power of love, or what?",
  "I can't hear the hi-hat.",
  "I change my hair every week-and-a-half, dude. Get used to it.",
  "I couldn't stop thinking about my stupid ex-girlfriend.",
  "I dislike you, capisce?",
  "I do too! I have tons of ideas about Rome!",
  "I don't hit girls!",
  "I don't know the meaning of the word.",
  "I don't think I can hit a girl. They're soft.",
  "I don't think I'd get fat. Why would I get fat?",
  "I forget, do sheep have curly tails or is that pigs?",
  "I forgot you guys don't have that in Canada.",
  "I gotta pee on her!... I mean, I gotta pee. Pee time.",
  "I guess Wallace!",
  "I had this totally weird dream...",
  "I have to go pee due to boredom.",
  "I have to order something really cool.",
  "I have to pee.",
  "I hear she kicks all kinds of ass.",
  "I hope so amigo. I don't want any more bad blood between exes. What do you say?",
  "I just woke up and you were in my dream. I dreamt that you were delivering me this package. Is that weird?",
  "I know of him.",
  "I know of it.",
  "I know they smell like cat pee.",
  "I know you play mysterious and aloof just to avoid getting hurt. And I know you have reasons for not wanting talk about your past. I want you to know that I don't care about any of that stuff. Because I'm in lesbians with you.",
  "I like elevators.",
  "I may need it for the rest of the week too... and the year.",
  "I mean, are you really happy, or are you really evil?",
  "I mean, I saw it. It's just the comic book is better than the movie. Hello.",
  "I meant, scum of the earth.",
  "I partake not in the meat, nor the breastmilk, nor the ovum, of any creature with a face.",
  "I said lesbians...",
  "I skimmed it.",
  "I think he's only dating her because she's old, you know? She's probably like 25! She's some fat-ass white girl, you know?",
  "I think I understand you, man. And now I have to kill you.",
  "I think I'm not getting something.",
  "I think Peter hates us for some reason. I mean, it's not our fault we can't afford rent and we come here every month to try to charm our way through, right?...Can you be serious for one second?",
  "I think this ex-boyfriends thing is messing with my head...",
  "I think we should get out of here.",
  "I think you mentioned she was fat.",
  "I used to know a guy who could do that. He said it wasn't that great.",
  "I want to have his adopted babies.",
  "I was just a little bi-curious.",
  "I was more alone when we were together than I ever was on my own.",
  "I was only dating Lucas until the minute Todd walked by. Guess that's not very nice, but I used to be kind of...like that. We hated everyone, we wrecked stuff, nobody cared. He punched a hole in the moon for me. It was pretty crazy. A week-and-a-half later, he told me his dad was sending him to Vegan Academy, so, I dumped him.",
  "I wish I could turn into a morphing ball and roll to the bathroom from here, instead of having to get up.",
  "I.. You're 22!.... 23.... 24? You're 19!!",
  "I... but... it's... not... it's totally... it's... Y... you're not the boss of... me?",
  "I'd rather be dead than go back. He's a creep, you're a bitch, and you all deserve each other.",
  "If I peed my pants, would you pretend I just got wet from the rain?",
  "If I say yes, will you sign for your damn package?",
  "If we win, it won't just be Knives wearing Sex Bom-Omb shirts. It'll be the cool kids, too.",
  "If you want something bad, you have to fight for it. Step up your game, Scott. Break out the L-word.",
  "I'll be good! Am I normally not--",
  "I'll leave you alone forever now.",
  "I'm assuming!",
  "I'm going for the Oscar this year.",
  "I'm going to hit you so hard.",
  "I'm in lesbians with you.",
  "I'm more than pretty good, Esé. I have my own skate company.",
  "I'm not a boy!",
  "I'm not sure. Isn't a \"parmesan\" like a rodent or something?",
  "I'm sending you back to Gideon in a thousand pieces, you slag!",
  "I'm sorry; I'm not usually like this.",
  "I'm sure I've seen that guy before.",
  "Is he... European?",
  "Is Ramona with you?",
  "Is that girl a boy too?",
  "Is the news that we suck, because I really don't think I can take it.",
  "Is there anywhere you don't work?",
  "Is this an Envy-related dream again?",
  "It is I, Matthew Patel. Consider our fight... BEGUN!",
  "It may live in infamy.",
  "It meant nothing. I didn't think it would count.",
  "It meant nothing?!",
  "It's all blue.",
  "It's amazing what we can do with computers these days.",
  "It's been a while.",
  "It's called a grind, bro.",
  "It's hot! Also? I'm hot, so enjoy it while you can.",
  "It's just nerves!",
  "It's milk and eggs, bitch.",
  "It's no biggie. Um. You know, I know it's early, but I don't think anything can get in the way of how I SHIT!",
  "It's not a race, guys!",
  "It's not dorky! And I'm scared! Why are you psychic?",
  "It's not your fault.",
  "It's over Tamara, seriously! He's an idiot and a loser and... and he's a loser and he's an idiot!",
  "I've kissed the lips that kissed you!",
  "Just a phase?",
  "Kick her in the balls!",
  "Knives is with Young Neil now; she's totally cool with it.",
  "Lesbian?",
  "Let's be friends based on mutual hate.",
  "Let's both be girls.",
  "Let's forget the whole thing. I'm getting really sick of not strangling her.",
  "Level with me... did we suck?",
  "Like, do I have ulterior motives or something? I'm offended, Kim.",
  "Like... with jet-packs.",
  "Listen, I know I can be hard to be around sometimes. I totally understand if you don't want to hang anymore.",
  "Look, I didn't write the gay rulebook. You got a problem with it, take it up with Liberace's ghost.",
  "Look, I know Todd was bad news, but are you saying Envy wasn't? We all have baggage.",
  "Look, I've dabbled in being a bitch. It's part of the reason I moved here. I was really hoping to just...leave it all behind me.",
  "Look, Scott. I'm going to issue an ultimatum.",
  "Man, that was way too fast.",
  "Maps are hard! I could draw it really good if it was a sheep.",
  "Maybe.",
  "Me and Kim? I can barely remember. It was high school. She had freckles.",
  "Meaning your precious Scott must defeat me with his own fists!",
  "Mm-hmm... Listen, as you know, I'm opening a new Chaos Theatre in Toronto, and the Sex Bobs are playing our grand opening tonight, and it would feel really weird for all of us if you weren't there. They just did a soundtrack, and the acoustics here are *amazing*!",
  "Mumble... mumble... scarred for life...",
  "My name is Knives Chau, and I'm a SCOTTAHOLIC!!",
  "Nah, I'm just forcing him. How is it, baby?",
  "Neil knows my parts.",
  "Neil, you were saying about \"she seems awesome\"?",
  "Never *censored* mind how I'm doing it!",
  "Next time, we don't date the girl with eleven evil ex-boyfriends.",
  "No breakup is painless; somebody always gets hurt. What about you and that girl, Knives? Who broke up with who?",
  "No vegan diet, no vegan powers!",
  "No, dude, it's not like that at all.",
  "No, I don't know the cheat code for Sonic 3. I'm very busy here, Scott. Will you please stop calling me?",
  "No, I just spilled hot cocoa on my crotch!",
  "No, it's just that you have this really convenient subspace highway running through your head that I like to use. It's, like, 3 miles in 15 seconds.",
  "No, no, I want to hang. It's... You know, the whole evil ex-boyfriend thing...",
  "No, really. Please. Be good.",
  "No, Scott! This fat-ass hurt me, and I will have my revenge!",
  "No, we broke up. Hey, check it out. I learned the bass line from Final Fantasy II.",
  "No, why would I get fat?",
  "No. I want to fight you for me.",
  "No. Not even. That was some total ass. I was the other guy.",
  "No. This is something I have to face. Myself.",
  "Not to her face.",
  "Note to minors: He is lying. Underage drinking is not at all hilarious.",
  "Now you listen close and you listen hard, bucko! The next click you hear is me hanging up. The one after that... Is me pulling the trigger!",
  "Now, why on Earth would you wanna do... that?",
  "Nuh-uh... They're cool. Like anime.",
  "Of course I'll be good!",
  "Oh boo-hoo, pussy boy.",
  "Oh God!",
  "Oh god!... oh man! This is a nightmare! Is this a nightmare? Wake up, wake up, wake up, wake up...!",
  "Oh! Dude!! I picked up this guy? Named Mobile?",
  "Oh, did she? I was just there. Played the Chaos Theater for Gideon. You know him, right?",
  "Oh, got any embarrassing stories?",
  "Oh, he'll be done. Real soon.",
  "Oh, hi. Do you want to know who in my class is gay?",
  "OH, MY GOD! He's dating a fatass hipster chick! I hate her stupid guts! He only likes her because she's old! She's probably, like, 25! Oh, she's just some fatass white girl, you know?!",
  "Oh, my God. You punched the highlights out of her hair. He punched the highlights out of her hair!",
  "Oh, relax. It was a phase.",
  "Oh, well, hey, listen, man. Don't worry about it.",
  "Oh, would you give it up!",
  "Oh, you've got a fight, all right.",
  "Oh. Do you wanna know who in my class is gay?",
  "Oh. Then, why don't you give me the Cliff Notes on how and why you ended up dating this A-hole.",
  "Oh? Do you have any embarrassing stories?",
  "OK, laytaz'!",
  "Okay, fine. I had to fight a guy to be with her, okay? I fought a crazy, 80-foot-tall purple-suited dude, and I had to fight 96 guys to get to him. He was flying and shooting lightning bolts from his eyes, okay? And I kicked him so hard that he saw the curvature of the Earth. Does that make you feel any better?",
  "Okay, first of all, in Trainspotting, remember how he was all freaking out and worried? That was because he knew it was sick and wrong and illegal. Secondly, remember how she was coercing him into dating her?",
  "Okay, let's start with Launchpad McQuack.",
  "Okay, maybe I didn't watch that movie carefully.",
  "Okay, presumeably, you may have just seen a dude's junk, and I'm very sorry for that... so is he.",
  "Okay, stop. It sounds retarded. You sound retarded. I'm breaking up with you.",
  "Okay, underwater pimp and ho party, Canadian politics circa 1972 but you're secretly Batman party, then that last one...",
  "Okay, you know how you only use 10% of your brain? That's because the other 90% is filled with curds and whey.",
  "Okay. From here on out, no girlfriends or girlfriend talk at practice, whether they're old, new, or \"new-new.\"",
  "Okey. Well, maybe, do you wanna hang out sometime? Get to know each other. You're the new kid on the block, right? I've lived here forever, so there are reasons for you to hang out with me.",
  "On April 4th, 7:30 pm, you partook a plate of chicken parmesan.",
  "One of your famous ultimatums?",
  "Ooh, can you put on something really morbid and horrible and Japanese?",
  "Ooh, go ahead and poke fun at my poor queenology, Canada boy.",
  "OPTION 1: Follow the balloons from left to right and top to bottom, then move on to the next panel, the way you learned it at that sissy school of yours.",
  "OPTION 2: Read each balloon in whatever order appeals to you most. Freestyle! It's your book now! Don't let the man tell you which direction to read!",
  "Other Excuse me, can we skip the dreamtime? Colour me not interested.",
  "Ovo-lacto-vegetarian, maybe.",
  "Ovo-what?",
  "P... pirates are in this year!!",
  "Pirates are in this year!",
  "Playtime?",
  "Prepare to die, obviously!",
  "Prepare to feel the wrath of the League of the Evil Exes.",
  "Rammy? Are you seriously calling her that?",
  "Ramona, I like your outfit. Affordable?",
  "Ramona, I love you. I'll love you forever. And I have dipping sauce for you! I'll be your dipping sauce bitch!",
  "Roxy?",
  "Save it! You're pretentious, this club sucks, I've got beef. Let's do it.",
  "Scott earned the Power of Love!",
  "Scott earned the Power of Self-Respect!",
  "Scott Pilgrim!!! Hey, buddy, welcome to the Chaos Theatre! Somebody get this man a drink. A Coke Zero, right?",
  "Scott! Get out of bed!",
  "Scott, are you waiting for the package you just ordered?",
  "Scott, if your life had a face, I would punch it in the balls. Seriously.",
  "Scott, if your life had a face, I would punch it.",
  "Scott, if your life had a face, I would punch it. I would punch your life in the face.",
  "Scott, it was the ninth grade. He was a skinny little snot-nosed brat. He asked me out 96 times and I finally said okay.",
  "Scott, that was not a good comeback.",
  "Scott, you are the salt of the earth.",
  "Scott, you know I love you. But I need my own bed tonight. It's for sex.",
  "Scotty, you can cheat on many girls as you like. But you can't... cheat... death.",
  "Seriously, are you wearing, um, a tan jacket? Like a spring jacket? And a hoodie?",
  "She has men dying at her feet!",
  "She's got a head start. I mean, I didn't know there was good music until, like, two months ago! Hey, this really burns.",
  "Short answer: being vegan just makes you better than most people.",
  "Shut up. Why are you wearing those wristband things, anyway? Don't they make you sweat?",
  "So how was the tour? You guys play with the Pixies? You're like a superstar now.",
  "So what do you think, Jimmy? Do they rock or suck?",
  "So what you're saying is we're dating?",
  "So who are we playing with?",
  "So, can you do a grindy thingy now?",
  "So, what can I *censored* get you?",
  "So, you think I could get a job at the... uh... bank?",
  "Somebody get me my board.",
  "Somehow the pantsless gay man is not bringing the romance, Scott. I think I'll bid you adieu.",
  "SOOOOOO SAD!!!",
  "Sorry? You just head-butted my boyfriend so hard he burst.",
  "Sounds like someone wants to get...funky.",
  "S-so, what's on Monday?",
  "Steal my boyfriend, taste my steel!",
  "Stephen... you know how, when a baby is first born, it just cries at the sheer horror of being alive?",
  "Sup? How's life? He seems nice.",
  "Sweet! A song for ME!",
  "Sweet! I love this one.",
  "Tell it to the cleaning lady on Monday.",
  "Tell me about it.",
  "That doesn't even rhyme!",
  "That doesn't sound so good, either.",
  "That gossipy bitch.",
  "That one was Halloween, so I think it gets a free pass.",
  "That was a test, Jimmy, and you passed.",
  "That was actually not bad for Scott.",
  "That's for me! That's for me, that's for me. Hey, you're here.",
  "THAT'S IT! YOU COCKY COCK! You'll pay for your crimes against humanity!",
  "That's not the actual title of the song.",
  "That's not what your mom said last night!",
  "That's really the whole story?",
  "That's right, Pilgrim... I actually know how to play bass.",
  "That's what they'll be saying about you on Sunday.",
  "The De-Veganizing Ray. Hit him!!",
  "The girl from earlier?",
  "The League of Evil Exes?",
  "The only thing separating me from her is the two minutes it's gonna take to kick your ass.",
  "The other L-word.",
  "Their first album is better than their first album.",
  "Then your ears are retarded.",
  "There are girls watching.",
  "There goes our deal.",
  "There was snot in his nose?",
  "There's a heat wave warning in effect, so I'm ordering you to get out of our furnace-like apartment and go somewhere air-conditioned lest you die.",
  "There's only enough for me and Rammy.",
  "They have a girl drummer?",
  "They... they haven't started playing yet.",
  "They're called jobs, something a *censored* ball like you wouldn't know anything about. And by the way, I can't *censored* believe you asked Ramona out after I specifically told you not to *censored* do that!",
  "This band sucks.",
  "This guy is such toast. Doesn't he know Scott's the best fighter in the province?",
  "This is happening, right?",
  "This is just another example of Scott Pilgrim being a lazy ass who doesn't fight his own battles!",
  "This is the back of the book.",
  "This is the best St. Joel's could muster?",
  "This moment with your hand on my boob?",
  "This school has boys, too.",
  "This song is called, \"I Am So Sad, I Am So Very, Very Sad\". Goes a little something like this.",
  "This song is for the guy who keeps yelling from the balcony, and it's called \"We Hate You, Please Die.\"",
  "Todd Ingram, you're under arrest for Veganity Violation Code Number 827: Imbibement of half-and-half.",
  "Uh, I don't think I can hit a girl. They're soft.",
  "Uh, Scott, we're gonna go to Pizza Pizza for a slice. Call us when you're done.",
  "Uh...sorry, I guess.",
  "Um, Envy... I read your blog.",
  "Um, no. That's okay. You just need to sign for this, alright?",
  "Um... Am I dreaming?",
  "Ve-gone?",
  "Wait who told you?",
  "Wait! We're fighting over Ramona?",
  "Wait, how does that work?",
  "Wait, wait, w-w-wait! You wanna fight me... for her?",
  "Wait, what? This sucks!",
  "Wallace, you go now. Begone.",
  "WARNING: for entertainment use only. Do not attempt to learn anything from this page.",
  "Was he swinging a huge samurai sword at your neck? Excuse me, through a streetcar at your neck?",
  "Was that not clear? …Was that not clear?",
  "We all have baggage.",
  "WE ARE SEX BOB-OMB AND WE ARE HERE TO MAKE YOU THINK ABOUT DEATH AND GET SAD AND STUFF!!!",
  "WE ARE SEX BOB-OMB AND WE ARE HERE TO WATCH SCOTT PILGRIM KICK YOUR TEETH IN!!!! ONE-TWO-THREE-FOUR!!!!",
  "We are Sex Bob-Omb. We are here to make money and sell out and stuff. One-two-three-four!",
  "We don't use the \"E\" word in this house.",
  "We have a mutual friend, see, and she- Ah, screw it. This is Gideon. When would it be convenient for you to die?",
  "We have an unfinished business. I and he.",
  "We have blueberry, raspberry, ginseng, sleepy time, green tea, green tea with lemon, green tea with lemon and honey, liver disaster, ginger with honey, ginger without honey, vanilla almond, white truffel, blueberry chamomile, vanilla walnut, constant comment and... earl grey.",
  "We have unfinished business, I and he.",
  "We were just on stage for sound check, and the sound guy hated us!",
  "We were lucky to survive the last round. It's sudden death now, okay?",
  "Well you kicked my heart in the ass.",
  "Well, 'cause... it's Friday now, she has the weekends off, so... Monday. Right?",
  "Well, hey, if it's too hardcore, then...",
  "Well, honey... I'm a little bi-furious!",
  "Well, if my cathedral of cutting-edge taste holds no interest for your tragically Canadian sensibilities, then I shall be forced to grant you a swift exit from the premises... and a fast entrance into hell!",
  "Well, if there's a key element in his backstory that's gonna help me out in a critical moment of not dying, yes.",
  "Well, it was nice to meet you and tell your gay friends I will see them later.",
  "Well, now you are being a total ass. Welcome to the club.",
  "Well, Pac-man was originally called Puck-man. They changed it because... Not because Pac-man looks like a hockey puck. \"Paku Paku\" means \"flap your mouth\", and they were worried that people would change, scratch out the P turn it into an F, like...",
  "Well, she's only allowed out when the sun is up, so I wouldn't call it dating. It's more like...",
  "Well, then Gideon best get his pretentious ass up here, 'cause I'm about to kick yours out of the Great White North!",
  "We're still getting paid, right?",
  "Were you the Pac-Man guy?",
  "Wh--? That's bullroar!",
  "What a perfect asshole.",
  "You should see them live. They're so much better live."
];
